-- local ls = require 'luasnip'
-- local s = ls.snippet
-- local t = ls.text_node
-- local i = ls.insert_node
-- local fmt = require('luasnip.extras.fmt').fmt
-- local fmta = require('luasnip.extras.fmt').fmta
--
-- local line_begin = require("luasnip.extras.expand_conditions").line_begin
--
-- local helper = require('luasnip-helper-funcs')
-- local in_math = helper.in_mathzone
-- local in_itemize = helper.in_itemize
--
-- local inner_snip = helper.inner_snip
-- local expression = helper.expression
-- local env_snip = helper.env_snip
--
--
--
--
-- local snippet_list = {}
--
-- local function thmbox(name, command, label)
--     local start_string = "\\begin{" .. command .. "}[<>]{<>}{<>}"
--     local end_string = "\\end{" .. command .. "}"
--     local fmta_val = start_string .. "\n\t<>\n" .. end_string
--
--     return s(
-- 	{trig=name, dscr=label},
-- 	fmta(fmta_val, {
-- 	    i(1, "Name"),
-- 	    i(2, "Label"),
-- 	    i(3, "Number"),
-- 	    i(4),
-- 	}),
-- 	{ condition = line_begin}
--     )
-- end
--
--
-- return {
--     -- Theorem Boxes
--     thmbox("add;thm", "thm", "Add a Theorem" ),
--     thmbox("add;def", "def", "Add a Definition" ),
--     thmbox("add;xmp", "xmp", "Add an Example" ),
--     thmbox("add;rem", "rem", "Add a Remark" ),
--
--     -- Single line named expressions
--     inner_snip("add;sc", "\\section*{<>}", "add a section", line_begin),
--     inner_snip("add;nsc", "\\section{<>}", "add a numbered section", line_begin),
--     inner_snip("add;ss", "\\subsection*{<>}", "add a subsection", line_begin),
--     inner_snip("add;nss", "\\subsection{<>}", "add a numbered subsection", line_begin),
--     inner_snip("add;pac", "\\usepackage{<>}", "add a package", line_begin),
--
--     -- Multi line named environments
--     env_snip("add;align", "align*", "add an align environment"),
--     env_snip("add;nalign", "align", "add a numbered align environment"),
--
--     -- No variable expressions
--     expression("add;bar", "\\noindent\\rule{\\textwidth}{0.2pt}", "Add a horizontal bar"),
--
--     -- Individual snippets
--     s(
-- 	{trig="add;img", dscr="Add an Image"},
-- 	fmta(
-- 	    [[
-- 	\begin{figure}[H]
-- 	    \centering
-- 	    \includegraphics[width=\linewidth]{<>}
-- 	\end{figure}
-- 	]],
-- 	    { i(1, "url")}
-- 	)
--     ),
--     s(
-- 	{trig="add;fig", dscr="Add a Figure"},
-- 	fmta(
-- 	    [[
-- 	\begin{figure}[h!]
-- 	    \centering
-- 	    \includegraphics[width=\linewidth]{<>}
-- 	    \caption{<>}
-- 	    \label{<>}
-- 	\end{figure}
-- 	]],
-- 	    {
-- 		i(1, "url"),
-- 		i(2, "Caption"),
-- 		i(3, "Label"),
-- 	    }
-- 	)
--     ),
--     s(
-- 	{trig="add;item", dscr="Add an itemized list"},
-- 	fmta(
-- 	    [[
-- 	\renewcommand\labelitemi{\tiny$\bullet$}
-- 	\begin{itemize}
-- 	    \item <>
-- 	\end{itemize}
-- 	]],
-- 	    {
-- 		i(1),
-- 	    }
-- 	)
--     ),
--
-- },
-- {
--     s(
-- 	{trig="%d", regTreg = true},
-- 	t("\\\\", "\\item "),
-- 	{ condition = in_itemize and line_begin}
--     )
-- }
