-- local dap = require 'dap'
-- local dapui = require 'dapui'
--
-- -- require('mason-nvim-dap').setup{
-- --   -- Makes a best effort to setup the various debuggers with
-- --   -- reasonable debug configurations
-- --   automatic_installation = true,
-- --
-- --   -- You can provide additional configuration to the handlers,
-- --   -- see mason-nvim-dap README for more information
-- --   handlers = {},
-- --
-- --   -- You'll need to check that you have the required things installed
-- --   -- online, please don't ask me how to install them :)
-- --   ensure_installed = {
-- --     -- Update this to ensure that you have the debuggers for the langs you want
-- --     'delve',
-- --   },
-- -- }
--
-- dap.configurations.python = {
--   {
--     type = 'python',
--     request = 'launch';
--     name = "Launch file";
--     program = "${file}";
--     pythonPath = function()
--       return 'python'
--     end;
--   },
--   {
--     type = 'python',
--     request = 'launch';
--     name = "Choco Opt";
--     program = "choco-opt -p all ${file}";
--     pythonPath = function()
--       return 'python'
--     end;
--   }
-- }
--
-- -- Dap UI setup
-- -- For more information, see |:help nvim-dap-ui|
-- dapui.setup {
--   -- Set icons to characters that are more likely to work in every terminal.
--   --    Feel free to remove or use ones that you like more! :)
--   --    Don't feel like these are good choices.
--   icons = { expanded = '▾', collapsed = '▸', current_frame = '*' },
--   controls = {
--     icons = {
--       pause = '⏸',
--       play = '▶',
--       step_into = '⏎',
--       step_over = '⏭',
--       step_out = '⏮',
--       step_back = 'b',
--       run_last = '▶▶',
--       terminate = '⏹',
--       disconnect = '⏏',
--     },
--   },
-- }
--
-- dap.listeners.after.event_initialized.dapui_config = function() dapui.open() end
-- dap.listeners.before.launch.dapui_config = function() dapui.open() end
-- dap.listeners.before.event_terminated.dapui_config = function() dapui.close() end
-- dap.listeners.before.event_exited.dapui_config = function() dapui.close() end
--
-- -- Install golang specific config
-- require('dap-go').setup()
--
-- require('dap-python').setup("python")
