-- local ls = require 'luasnip'
-- local s = ls.snippet
-- local t = ls.text_node
-- local i = ls.insert_node
-- local helper = require('luasnip-helper-funcs')
-- local fmta = require('luasnip.extras.fmt').fmta
--
-- local line_begin = require("luasnip.extras.expand_conditions").line_begin
-- local inMath = helper.in_mathzone
-- local inner_snip = helper.inner_snip
--
-- local snippet_list = {}
--
-- local manual_snippet_list = {
--     inner_snip("floor", "\\lfloor <> \\rfloor", "Floor function", inMath ),
--     inner_snip("ceil", "\\lceil <> \\rceil", "Ceiling function", inMath ),
--
--     inner_snip("avg", "\\langle <> \\rangle", "Angled Braces", inMath ),
--     inner_snip("abs", "\\lvert <> \\rvert", "Absolute Value, inMath"),
--     inner_snip("norm", "\\lVert <> \\rVert", "Double Abs, inMath"),
-- }
--
-- -- Combine automated lists with manual list
-- for _, snippet in ipairs(manual_snippet_list) do
--     table.insert(snippet_list, snippet)
-- end
--
-- return {}, snippet_list
